# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
     - main
  paths:
    include:
     - apis/trips

pr:
  branches:
    include:
    - main
  paths:
    include:
     - apis/trips

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.16.8'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'

#- task: Go@0
#  inputs:
#    command: 'test'
#    arguments: './tripsgo -run Unit -coverprofile=coverage.txt -covermode count | go-junit-report > trips-report.xml'
#    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
- script: |
    go get github.com/jstemmer/go-junit-report
    go test ./tripsgo -run Unit -coverprofile=coverage.txt -covermode count | go-junit-report > trips-report.xml
  workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
  displayName: 'Run unit test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/trips-report.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/apis/trips'
    failTaskOnFailedTests: true
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
