# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
     - main
  paths:
    include:
     - apis/trips
     - azure-api-trips.yml

pr:
  branches:
    include:
    - main
  paths:
    include:
     - apis/trips
     - azure-api-trips.yml

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.16.8'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
#- task: Go@0
#  inputs:
#    command: 'get'
#    arguments: 'github.com/jstemmer/go-junit-report'
#    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips/tripsgo'
- task: Go@0
  inputs:
    command: 'test'
    arguments: './tripsgo -run Unit'
#    arguments: './tripsgo -run Unit -coverprofile=coverage.txt -covermode count | go-junit-report > trips-report.xml'
    workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
    
#- script: |    
#    go test -run Unit -coverprofile=coverage.txt -covermode count 2>&1 | go-junit-report > trips-report.xml
#  workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips/tripsgo'
#  displayName: 'Run unit test'

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'acr-openhack-team5'
    repository: 'devopsoh/api-trips'
    command: 'build'
    Dockerfile: '$(System.DefaultWorkingDirectory)/apis/trips/Dockerfile'
    arguments: --build-arg build_version = $(Build.BuildId)

- task: Docker@2
  displayName: Push an image
  inputs:
    containerRegistry: 'acr-openhack-team5'
    repository: 'devopsoh/api-trips'
    command: 'Push'